version: '3.4'
services:
  iam:
    ports:
      - 5050:5050
    tty: true
    stdin_open: true
  web:
    ports:
      - 5000:80
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:alpine
    volumes:
      - /var/lib/postgresql/data
